
create table census2018


(

CLASS character varying(255),
CLASS_CODE character varying(255),
COMM_CODE character varying(255),
NAME character varying(255),
SECTOR character varying(255), 
SRG character varying(255),
COMM_STRUCTURE character varying(255),
CNSS_YR character varying(255),
FOIP_IND character varying(255),
RES_CNT character varying(255),
DWELL_CNT character varying(255),
PRSCH_CHLD character varying(255),
ELECT_CNT character varying(255),
EMPLYD_CNT character varying(255),
OWNSHP_CNT character varying(255),
DOG_CNT character varying(255),
CAT_CNT character varying(255),
PUB_SCH character varying(255),
SEP_SCH character varying(255),
PUBSEP_SCH character varying(255),
OTHER_SCH character varying(255),
UNKNWN_SCH character varying(255),
SING_FAMLY character varying(255),
DUPLEX character varying(255),
MULTI_PLEX character varying(255),
APARTMENT character varying(255),
TOWN_HOUSE character varying(255),
MANUF_HOME character varying(255),
CONV_STRUC character varying(255),
COMUNL_HSE character varying(255),
RES_COMM character varying(255),
OTHER_RES character varying(255),
NURSING_HM character varying(255),
OTHER_INST character varying(255),
HOTEL_CNT character varying(255),
OTHER_MISC character varying(255),
APT_NO_RES character varying(255),
APT_OCCPD character varying(255),
APT_OWNED character varying(255),
APT_PERSON character varying(255),
APT_VACANT character varying(255),
APT_UC character varying(255),
APT_NA character varying(255),
CNV_NO_RES character varying(255),
CNV_OCCPD character varying(255),
CNV_OWNED character varying(255),
CNV_PERSON character varying(255),
CNV_VACANT character varying(255),
CNV_UC character varying(255),
CNV_NA character varying(255),
DUP_NO_RES character varying(255),
DUP_OCCPD character varying(255),
DUP_OWNED character varying(255),
DUP_PERSON character varying(255),
DUP_VACANT character varying(255),
DUP_UC character varying(255),
DUP_NA character varying(255),
MFH_NO_RES character varying(255),
MFH_OCCPD character varying(255),
MFH_OWNED character varying(255),
MFH_PERSON character varying(255),
MFH_VACANT character varying(255),
MFH_UC character varying(255),
MFH_NA character varying(255),
MUL_NO_RES character varying(255), 
MUL_OCCPD character varying(255),
MUL_OWNED character varying(255),
MUL_PERSON character varying(255),
MUL_VACANT character varying(255),
MUL_UC character varying(255),
MUL_NA character varying(255),
OTH_NO_RES character varying(255),
OTH_OCCPD character varying(255),
OTH_OWNED character varying(255),
OTH_PERSON character varying(255),
OTH_VACANT character varying(255),
OTH_UC character varying(255),
OTH_NA character varying(255),
TWN_NO_RES character varying(255),
TWN_OCCPD character varying(255),
TWN_OWNED character varying(255),
TWN_PERSON character varying(255),
TWN_VACANT character varying(255),
TWN_UC character varying(255),
TWN_NA character varying(255),
SF_NO_RES character varying(255),
SF_OCCPD character varying(255),
SF_OWNED character varying(255),
SF_PERSON character varying(255),
SF_VACANT character varying(255),
SF_UC character varying(255),
SF_NA character varying(255),
OTH_STRTY character varying(255),
DWELSZ_1 character varying(255),
DWELSZ_2 character varying(255),
DWELSZ_3 character varying(255),
DWELSZ_4_5 character varying(255),
DWELSZ_6 character varying(255),
MALE_CNT character varying(255),
FEMALE_CNT character varying(255),
MALE_0_4 character varying(255),
MALE_5_14 character varying(255),
MALE_15_19 character varying(255),
MALE_20_24 character varying(255),
MALE_25_34 character varying(255),
MALE_35_44 character varying(255),
MALE_45_54 character varying(255),
MALE_55_64 character varying(255),
MALE_65_74 character varying(255),
MALE_75 character varying(255),
FEM_0_4 character varying(255),
FEM_5_14 character varying(255),
FEM_15_19 character varying(255),
FEM_20_24 character varying(255),
FEM_25_34 character varying(255),
FEM_35_44 character varying(255),
FEM_45_54 character varying(255),
FEM_55_64 character varying(255),
FEM_65_74 character varying(255),
FEM_75 character varying(255),
MF_0_4 character varying(255),
MF_5_14 character varying(255),
MF_15_19 character varying(255),
MF_20_24 character varying(255),
MF_25_34 character varying(255),
MF_35_44 character varying(255),
MF_45_54 character varying(255),
MF_55_64 character varying(255),
MF_65_74 character varying(255),
MF_75 character varying(255),
multipolygon character varying(1000),
CONSTRAINT census2018_pkey PRIMARY KEY (COMM_CODE)
)

ALTER TABLE public.census2018
    ALTER COLUMN multipolygon TYPE text

copy census2018 (class, class_code, comm_code, name, sector, srg, comm_structure, cnss_yr, foip_ind, res_cnt, dwell_cnt, prsch_chld, elect_cnt, emplyd_cnt, ownshp_cnt, dog_cnt, cat_cnt, pub_sch, sep_sch, pubsep_sch, other_sch, unknwn_sch, sing_famly, duplex, multi_plex, apartment, town_house, manuf_home, conv_struc, comunl_hse, res_comm, other_res, nursing_hm, other_inst, hotel_cnt, other_misc, apt_no_res, apt_occpd, apt_owned, apt_person, apt_vacant, apt_uc, apt_na, cnv_no_res, cnv_occpd, cnv_owned, cnv_person, cnv_vacant, cnv_uc, cnv_na, dup_no_res, dup_occpd, dup_owned, dup_person, dup_vacant, dup_uc, dup_na, mfh_no_res, mfh_occpd, mfh_owned, mfh_person, mfh_vacant, mfh_uc, mfh_na, mul_no_res, mul_occpd, mul_owned, mul_person, mul_vacant, mul_uc, mul_na, oth_no_res, oth_occpd, oth_owned, oth_person, oth_vacant, oth_uc, oth_na, twn_no_res, twn_occpd, twn_owned, twn_person, twn_vacant, twn_uc, twn_na, sf_no_res, sf_occpd, sf_owned, sf_person, sf_vacant, sf_uc, sf_na, oth_strty, dwelsz_1, dwelsz_2, dwelsz_3, dwelsz_4_5, dwelsz_6, male_cnt, female_cnt, male_0_4, male_5_14, male_15_19, male_20_24, male_25_34, male_35_44, male_45_54, male_55_64, male_65_74, male_75, fem_0_4, fem_5_14, fem_15_19, fem_20_24, fem_25_34, fem_35_44, fem_45_54, fem_55_64, fem_65_74, fem_75, mf_0_4, mf_5_14, mf_15_19, mf_20_24, mf_25_34, mf_35_44, mf_45_54, mf_55_64, mf_65_74, mf_75, multipolygon) FROM '/home/giovas/Desktop/Census_by_Community_2018.csv' DELIMITER ',' CSV HEADER ENCODING 'UTF8' 



create table firestations
(
NAME character varying(255),
ADDRESS character varying(255),
STN_NUM character varying(255),
COMMUNITY character varying(255),
GLOBALID character varying(255),
NON_EMERGENCY_INFO character varying(255),
CREATED_DT character varying(255),
MODIFIED_DT character varying(255),
MODIFIED_ACTION character varying(255),
Point TEXT,
CONSTRAINT firestations_pkey PRIMARY KEY (NAME)
)

copy firestations (NAME,ADDRESS,STN_NUM,COMMUNITY,GLOBALID,NON_EMERGENCY_INFO,CREATED_DT,MODIFIED_DT,MODIFIED_ACTION,Point) FROM '/home/giovas/Desktop/Calgary_Fire_Stations.csv' DELIMITER ',' CSV HEADER ENCODING 'UTF8'

create table emstations
(
ADDRESS character varying(255),
COMM_CODE character varying(255),
NAME character varying(255),
TYPE character varying(255),
longitude character varying(255),
latitude character varying(255),
point character varying(255),
"Ward Boundaries" character varying(255),
"City Quadrants" character varying(255),
"Calgary Communities" character varying(255),
"Ward Boundaries 2013-2017" character varying(255),
CONSTRAINT emstations_pkey PRIMARY KEY (NAME)

)


copy emstations (ADDRESS,COMM_CODE,NAME,TYPE,longitude,latitude,point,"Ward Boundaries","City Quadrants","Calgary Communities","Ward Boundaries 2013-2017"
)FROM '/home/giovas/Desktop/EMS_Stations.csv' DELIMITER ',' CSV HEADER ENCODING 'UTF8'
